SECONDS_IN_HOUR=3600
HOURS_IN_DAY=24
SECONDS_IN_DAY=HOURS_IN_DAY*SECONDS_IN_HOUR

ACTION="action"
VEHICLE="vehicle"
DATETIME="datetime"
TICKET_ID = "ticket_id"
LOCATION = "location"
ACTIVITY="activity"
